compact: true
directory:
  - .
download-external-modules: false
evaluate-variables: true
external-checks-dir: []
framework:
  - terraform
output: cli
quiet: false
skip-check: []
skip-path:
  - .terraform
  - spec
soft-fail: false
