name: PR Build & Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - '**'
      - '!main'  # Exclude main branch to avoid duplicate runs on PRs

permissions:
  contents: write
  packages: write
  checks: write  # Required for creating check runs
  pull-requests: write  # Required for commenting on PRs
  actions: write  # Required for cache operations

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:master
            network=host

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Docker setup
        run: |
          docker version
          docker info
          docker buildx ls
          docker buildx inspect --bootstrap

      - name: Debug environment
        run: |
          pwd
          ls -la
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ github.repository }}/rover:pr-${{ github.sha }}
          file: ${{ github.workspace }}/Dockerfile
          target: base
          build-args: |
            TARGETARCH=amd64
            TARGETOS=linux
            USER_UID=1000
            USER_GID=1000
            USERNAME=vscode
            versionVault=1.15.0
            versionGolang=1.21.6
            versionKubectl=1.28.4
            versionKubelogin=0.1.0
            versionDockerCompose=2.24.1
            versionTerraformDocs=0.17.0
            versionPacker=1.10.0
            versionPowershell=7.4.1
            versionAnsible=2.16.2
            extensionsAzureCli=aks-preview
            versionTerrascan=1.18.3
            versionTfupdate=0.7.2
            TARGETARCH=amd64
            TARGETOS=linux
            USER_UID=1000
            USER_GID=1000
            USERNAME=vscode
            versionVault=1.15.0
            versionGolang=1.21.6
            versionKubectl=1.28.4
            versionKubelogin=0.1.0
            versionDockerCompose=2.24.1
            versionTerraformDocs=0.17.0
            versionPacker=1.10.0
            versionPowershell=7.4.1
            versionAnsible=2.16.2
            extensionsAzureCli=aks-preview
            versionTerrascan=1.18.3
            versionTfupdate=0.7.2
          
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ github.repository }}/rover:pr-${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Report build status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const { number } = context.issue;
            const status = '${{ job.status }}' === 'success' ? '✅' : '❌';
            
            let body = `Build Status: ${status}

Build Information:
- Platforms: linux/amd64, linux/arm64
- SHA: ${context.sha}
- Security: Trivy scan results uploaded to Security tab

Status Details:
- Build: ${status}
- Security Scan: ${process.env.TRIVY_EXIT_CODE === '0' ? '✅' : '❌'}`;
            
            if (context.payload.pull_request) {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: number,
                body
              });
            }
            
            // Set status check
            const conclusion = '${{ job.status }}' === 'success' ? 'success' : 'failure';
            await github.rest.checks.create({
              owner,
              repo,
              name: 'Build & Security Check',
              head_sha: context.sha,
              status: 'completed',
              conclusion,
              output: {
                title: `Build ${status}`,
                summary: body
              }
            });
