name: Release Build

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/rover
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          
      - name: Run MSDO scan for base image
        uses: microsoft/security-devops-action@v1
        id: msdo-base
        with:
          categories: containers
          
      - name: Upload MSDO scan results for base image
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: '${{ steps.msdo-base.outputs.sarifFile }}'
          category: 'MSDO-Release-Base'
          wait-for-processing: true
          
      - name: Run MSDO scan for agents
        uses: microsoft/security-devops-action@v1
        id: msdo-agents
        with:
          categories: containers
          image: |
            ghcr.io/${{ github.repository }}/rover-agent:latest-github
            ghcr.io/${{ github.repository }}/rover-agent:latest-tfc
            ghcr.io/${{ github.repository }}/rover-agent:latest-gitlab
            ghcr.io/${{ github.repository }}/rover-agent:latest-azure_devops
          
      - name: Upload MSDO scan results for agents
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: ${{ steps.msdo-agents.outputs.sarifFile }}
          category: 'MSDO-Release-Agents'
          wait-for-processing: true

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Report build status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const status = '${{ job.status }}' === 'success' ? '✅' : '❌';
            
            // Create check run
            await github.rest.checks.create({
              owner,
              repo,
              name: 'Release Build & Security Check',
              head_sha: context.sha,
              status: 'completed',
              conclusion: '${{ job.status }}' === 'success' ? 'success' : 'failure',
              output: {
                title: `Release Build ${status}`,
                summary: `Build Status: ${status}

Build Information:
- Platforms: linux/amd64, linux/arm64
- Security: MSDO analysis complete (includes container security scanning)
- Images: ${steps.meta.outputs.tags}`
              }
            });
