name: Build Rover preview images

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-flags: --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: rover:preview
        platforms: linux/amd64
        push: false
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@latest
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
    #   with:
    #     tag_name: ${{ env.docker_tag }}
    #     release_name: aztfmod/rover:${{ env.docker_tag }}
    #     draft: false
    #     prerelease: true
