name: Test Building Roverlight on PR

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    
    - name: Generate tags
      id: tag
      run: echo "date=$(date +'%g%m.%d%H%M')" >> $GITHUB_OUTPUT
          
    - name: Test Building
      uses: docker/bake-action@v4
      with:
        push: false
        load: true
        targets: roverlight

    - name: Scan container
      uses: anchore/scan-action@v3
      id: scan
      with:
        image: "roverlight:latest"
        severity-cutoff: critical

    - name: Upload scan SARIF report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}