name: Roverlight-Test-Build-On-PR

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-${{ matrix.platform }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.platform }}-buildx-
    
    - name: Generate tags
      id: tag
      run: echo "date=$(date +'%g%m.%d%H%M')" >> $GITHUB_OUTPUT
          
    - name: Test Building
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.roverlight
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        build-args: |
          versionRover=${{ steps.tag.outputs.date }}
        push: false
        load: true
        tags: roverlight:${{ steps.tag.outputs.date }}, roverlight:latest_test
        platforms: ${{ matrix.platform }}

    - name: Scan container
      uses: anchore/scan-action@v3
      id: scan
      with:
        image: roverlight:${{ steps.tag.outputs.date }}
        severity-cutoff: critical

    - name: Upload scan SARIF report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}