name: Roverlight-Test-Build-On-PR

on:
  pull_request:

permissions:
  contents: read
  packages: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: 
          - linux/amd64 
          - linux/arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkit-flags: |
          --debug
          --allow-insecure-entitlement security.insecure
          --allow-insecure-entitlement network.host
    
    - name: Generate tags
      id: tag
      run: echo "date=$(date +'%g%m.%d%H%M')" >> $GITHUB_OUTPUT
          
    - name: Docker Hub Login
      if: false
      uses: docker/login-action@v3
      with:
        username: aztfmod
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Testing roverlight
      id: push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.roverlight
        cache-from: type=gha,scope=${{ matrix.platform }}
        cache-to: type=gha,mode=max,scope=${{ matrix.platform }}
        build-args: |
          versionRover=${{ steps.tag.outputs.date }}
        push: false
        load: ${{ matrix.platform == 'linux/amd64' }}
        platforms: ${{ matrix.platform }}
        tags: ghcr.io/${{ github.repository }}/rover/roverlight:${{ steps.tag.outputs.date }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Scan container
      if: matrix.platform == 'linux/amd64'
      uses: anchore/scan-action@v3
      id: scan
      with:
        image: ghcr.io/${{ github.repository }}/rover/roverlight:${{ steps.tag.outputs.date }}
        severity-cutoff: critical

    - name: Upload scan SARIF report
      if: matrix.platform == 'linux/amd64'
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
