name: Unit Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install ShellSpec
      run: |
        curl -fsSL https://git.io/shellspec | sh -s -- --yes
        echo "${HOME}/.local/bin" >> $GITHUB_PATH

    - name: Run Unit Tests
      run: |
        shellspec --format documentation

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          .shellspec-report/
          coverage/

    - name: Microsoft Security DevOps
      uses: microsoft/security-devops-action@v1
      with:
        categories: 'IaC,containers'
