name: Unit Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq uuid-runtime
        curl -fsSL https://git.io/shellspec | sh -s -- --yes
        echo "${HOME}/.local/bin" >> $GITHUB_PATH

    - name: Setup Test Environment
      run: |
        mkdir -p /tmp/test_logs
        mkdir -p scripts/tfcloud
        touch scripts/tfcloud/mock.sh
        export log_folder_path="/tmp/test_logs"
        export script_path="$(pwd)/scripts"

    - name: Run Unit Tests
      run: |
        export log_folder_path="/tmp/test_logs"
        shellspec --format documentation spec/unit/logger/logger_spec.sh

    - name: Generate Coverage Report
      run: |
        shellspec --coverage --kcov-options "--include-path=scripts/lib" spec/unit/logger/logger_spec.sh

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          .shellspec-report/
          coverage/
          /tmp/test_logs/

    - name: Microsoft Security DevOps
      uses: microsoft/security-devops-action@v1
      with:
        categories: 'IaC'
